[General] Restyle and re-layout chips (more dense)
iurii-vatazhyshyn/ui pull request #42
Opened 2021-06-10 10:14 UTC by iurii-vatazhyshyn

https://trello.com/c/PUNXb5iD/853-general-restyle-and-re-layout-chips-more-dense

2021-06-14 10:05 UTC, mavdryk requested changes

2021-06-14 10:05 UTC, mavdryk commented on src/common/Chip/Chip.js
> +import { CHIP_MATCHES } from '../../types'
rename to `CHIP_OPTIONS`

2021-06-14 10:05 UTC, mavdryk commented on src/common/Chip/Chip.js
> +  const [chipWidth, setChipWidth] = React.useState(0)
use name import and get rid of `React`

2021-06-14 10:05 UTC, mavdryk commented on src/common/Chip/Chip.js
> +  const refWrapper = React.useRef()
use name import and get rid of `React`

2021-06-14 10:05 UTC, mavdryk commented on src/common/ChipCell/ChipCell.js
> +  chipOptions: PropTypes.shape({}),
use constant from `types` file

2021-06-15 08:40 UTC, mariana-furyk commented on src/common/Chip/Chip.js
> +  chipCellRef,
don't pass refs as a simple prop, you should use forwardRef always

2021-06-15 08:40 UTC, mariana-furyk commented on src/elements/ChipForm/ChipForm.js
> +  const maxWidthInput = chipCellRef?.current?.clientWidth - 45
add this value to state because it has dependency on chipCellRef

2021-06-15 08:40 UTC, mariana-furyk commented on src/elements/DetailsInfoItem/DetailsInfoItem.js
> +  chipOptions: PropTypes.shape({}),
```suggestion
  chipOptions: CHIP_OPTIONS,
```

2021-06-17 12:33 UTC, closed without merging